CREATE DATABASE customer_behavior;
use customer_behavior;

Alter table mytable
Rename to customer;

-- Q.1 What is the total revenue generated by Male vs Female Customers
Select gender, sum(purchase_amount) as revenue
From customer
group by gender;

-- Q.2 Which customer used a discount but still spent more than the average purchase amount.
Select customer_id, purchase_amount
From customer
where discount_applied="Yes" and purchase_amount>=(Select(AVG(purchase_amount))
From customer);

-- Q.3 Which are the top 5 products  with highest average review rating
Select item_purchased, Round(AVG(review_rating),2)  as "avg_review_rating"
From customer
group by item_purchased
order by AVG(review_rating) DESC
LIMIT 5;

-- Q.4 Compare the average purchase amount between standard and express shiping
select shipping_type ,Round(AVG(purchase_amount),2) as "avg_purchase_amount"
from customer
Where shipping_type in ('Standard','Express')
group by shipping_type;

-- Q.5 Do subscribed customers spend more compare average spend and total revenue 
-- between subscribers and non subscribers
select subscription_status, COUNT(customer_id) as total_customer,
Round(AVG(purchase_amount),2) as  avg_spend,
Round(SUM(purchase_amount),2) as total_revenue
from customer
group by subscription_status
order by total_revenue,avg_spend DESC;

-- Q.6 Which 5 products have the highest percentage of purchase with discount applied
select item_purchased,
Round(100 * SUM(CASE WHEN discount_applied = "Yes" THEN 1 ELSE 0 END)/COUNT(*),2)
AS discount_rate
from customer
group by item_purchased
order by discount_rate DESC
LIMIT 5;

-- Q.7 Segment customer into New, Returning and Loyal based on their total number of
-- previous purchase and show the count of each segment
with customer_type as (
select customer_id, previous_purchases,
CASE 
WHEN previous_purchases =1 THEN "New"
WHEN previous_purchases Between 2 and 10 THEN "Returning"
ELSE"Loyal"
END as customer_segment
from customer
)
select customer_segment,count(customer_id) as "Number_of_Customers"
from customer_type
group by customer_segment;

-- Q.8 What are top 3 most purchased product within each category
with item_counts as (
select category,item_purchased,
COUNT(customer_id ) as total_orders,
ROW_NUMBER() OVER (partition by category order by COUNT(customer_id) DESC)
as item_rank from customer
group by category, item_purchased
)
select item_rank,category,item_purchased,total_orders
from item_counts
where item_rank<=3;

-- Q.9 Are customers who are repeat buyers (more then 5 previous purchase) also likely 
-- to subscribe
select subscription_status,Count(customer_id) as repeat_buyers
from customer
where previous_purchases >5
group by subscription_status;

-- Q.10 What is the revenue distribution of each age group
select  age_group, sum(purchase_amount) as total_revenue
from customer
group by age_group;